### ISSUE TITLE
Contact distribution vs. offspring distribution

### ISSUE THREAD

**Issue by sbfnk** [epiverse-trace/simulist#35]
If I understand correctly then what is currently called a contact distribution is actually an offspring distribution - if it was a contact distribution then for anyone after the initial case the number of offspring would have to be drawn from $q(n)\sim(n+1)p(n+1)$ if $p(n)$ is the probability of having $n$ contacts (because choosing someone at random by following up a contact chooses individuals with probability proportional to their number of contacts). The plus 1 is because one of the contacts was "used" to infect the person.

**Comment by joshwlambert** [comment]
The contact distribution, as it is currently implemented (let me know if it should be renamed) is used to generate random numbers of contacts per cases that did not get infected. The offspring distribution is fixed in `bpmodel::chain_sim()` (`.sim_bp_linelist()`). 

At the moment, the offspring and contact distribution are independent. The offspring distribution is used to produce the infected cases, and the contact distribution is used to produce the non-infected. The reason for including the contact distribution was to give some functional form (that can be changed by the user) to the randomness when producing the contacts table for those not infected.

**Comment by joshwlambert** [comment]
@sbfnk and I have met to discuss this issue and best approach to solve it. This issue stems from the method/architecture of how infections are initially simulated with a branching process model (`bpmodels::chain_sim()`) and then the contacts for each infected individual are attached by sampling from a contact distribution. Ideally, these two steps should be simulated in a single process, with the above _friendship/network effect_ as pointed out in the original comment included.

Therefore, the agreed next step (Seb please correct if you disagree) is to implement a network branching process simulation that can produce contacts and infections given a contact/degree distribution and a probability of infection per contact. Where this functionality will live long-term is not yet decided, but it could eventually be ported to one of the Epiverse-TRACE R packages on branching processes. 

I will create a new issue to outline the aims specific to the problem, and close this issue.
